Litma/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),  # 默认首页
    path('literature/', include('literature.urls')),
    path('project/', include('project.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

literature/urls.py
# literature/urls.py

from django.urls import path
from . import views


app_name = 'literature'
urlpatterns = [
    path('', views.literature_list, name='literature_list'),
    path('literature/<int:pk>/', views.literature_detail, name='literature_detail'),
    path('literature/create/', views.literature_create, name='literature_create'),
    path('literature/<int:pk>/update/', views.literature_update, name='literature_update'),
    path('literature/<int:pk>/delete/', views.literature_delete, name='literature_delete'),
    path('literature/<int:pk>/upload_attachment/', views.upload_attachment, name='upload_attachment'),
    path('import/', views.literature_import, name='literature_import'),
    
]

literature/models.py
# literature/models.py
import os
from django.db import models
from django.utils.deconstruct import deconstructible
from django.utils import timezone

def attachment_upload_path(instance, filename):
    # Replace '/' with '_' in DOI
    doi_safe = instance.literature.doi.replace('/', '_')
    # Return the upload path
    return os.path.join('literature', doi_safe, filename)

class Journal(models.Model):
    journal_fullname = models.CharField(max_length=200)
    journal_abbr = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.journal_fullname

class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

class Literature(models.Model):
    title = models.CharField(max_length=200)
    journal_abbr = models.CharField(max_length=100, blank=True)
    publication_year = models.CharField(max_length=10, blank=True, null=True)
    doi = models.CharField(max_length=200, unique=True)
    journal = models.ForeignKey(Journal, on_delete=models.SET_NULL, null=True, blank=True)
    projects = models.ManyToManyField(Project, related_name='literatures', null=True, blank=True)


    
    def save(self, *args, **kwargs):
        # Check if the journal exists, if not create it
        if self.journal_abbr:
            journal, created = Journal.objects.get_or_create(
                journal_abbr=self.journal_abbr,
                defaults={'journal_fullname': self.journal_abbr}  # You can adjust this logic as needed
            )
            self.journal = journal
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.attachment_set.all().delete()
        #if self.file:
        #    if os.path.isfile(self.file.path):
        #        os.remove(self.file.path)
        super().delete(*args, **kwargs)

    def has_attachments(self):
        """
        Check if the literature has any attachments.
        """
        return self.attachment_set.exists()

    def __str__(self):
        return self.title

class Attachment(models.Model):
    literature = models.ForeignKey(Literature, on_delete=models.CASCADE)
    file = models.FileField(upload_to=attachment_upload_path)
    uploaded_at = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=200, null=True, blank=True)  # 添加了一个描述字段

    def __str__(self):
        return self.file.name
    

literature/forms.py
#literature/forms.py

from django import forms
from .models import Literature, Attachment, Project

class LiteratureForm(forms.ModelForm):
    class Meta:
        model = Literature
        fields = ['title', 'journal_abbr', 'publication_year', 'doi', 'projects']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'journal_abbr': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Journal Abbr'}),
            'publication_year': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Publication Year'}),
            'doi': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DOI'}),
            'projects': forms.CheckboxSelectMultiple(attrs={'class': 'ms-3'})
        }


        

class AttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ['file', 'description']  
        widgets = {
            'description': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter Description'}),
            'file': forms.ClearableFileInput(attrs={}),
        }


#    def clean_file(self):
#        file = self.cleaned_data['file']
#        # 文件大小不能超过10MB
#        if file.size > 10 * 1024 * 1024:
#            raise forms.ValidationError("File size cannot exceed 10MB.")
#        # 仅允许上传PDF和文本文件
#        content_type = file.content_type
#        if content_type not in ['application/pdf', 'text/plain']:
#            raise forms.ValidationError("Only PDF and plain text files are allowed.")
#        return file
    
class ImportForm(forms.Form):
    file = forms.FileField(label='Select a CSV file')


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Project Name'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description'}),
        }

literature/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Literature, Attachment, Project
from .forms import ImportForm, LiteratureForm, AttachmentForm, ProjectForm
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib import messages
import os,csv,tempfile
from django.core.files.storage import FileSystemStorage
import os

def literature_list(request):
    literatures = Literature.objects.all()
    return render(request, 'literature/literature_list.html', {'literatures': literatures})

def literature_create(request):
    if request.method == 'POST':
        form = LiteratureForm(request.POST)
        if form.is_valid():
            literature = form.save()
            return redirect('literature:literature_detail', pk=literature.pk)
    else:
        form = LiteratureForm()
    return render(request, 'literature/literature_form.html', {'form': form})


def literature_update(request, pk):
    literature = get_object_or_404(Literature, pk=pk)
    if request.method == 'POST':
        form = LiteratureForm(request.POST, instance=literature)
        if form.is_valid():
            form.save()
            return redirect('literature:literature_detail', pk=literature.pk)
    else:
        form = LiteratureForm(instance=literature)
    return render(request, 'literature/literature_form.html', {'form': form})

from django.shortcuts import redirect


def literature_delete(request, pk):
    literature = get_object_or_404(Literature, pk=pk)
    
    # 如果是POST请求，则执行删除操作
    if request.method == 'POST':
        literature.delete()
        
        data = {'success': True}
        # 返回一个JSON响应表示删除成功
        return JsonResponse(data)
        
        # 获取Referer头信息，即用户点击删除前所在的页面URL
        referer_url = request.META.get('HTTP_REFERER')
        
        # 如果Referer存在，则重定向到该页面；否则默认回到literature_list
        if referer_url:
            return HttpResponseRedirect(referer_url)
        else:
            return redirect('literature:literature_list')
    
    # 如果不是POST请求（例如GET请求查看删除确认页面），则返回到详情页或显示确认页面
    return redirect('literature:literature_detail', pk=pk)


#def literature_delete(request, pk):
#    literature = get_object_or_404(Literature, pk=pk)
#    if request.method == 'POST':
#        literature.delete()
#        return redirect('literature:literature_list')
#    return redirect('literature:literature_detail', pk=pk)


def literature_detail(request, pk):
    literature = get_object_or_404(Literature, pk=pk)
    attachments = literature.attachment_set.all()
    
    if request.method == "POST":
        if 'delete_attachment' in request.POST:
            attachment_id = request.POST['delete_attachment']
            attachment = Attachment.objects.get(pk=attachment_id)
            # 获取附件的文件路径
            attachment_file_path = attachment.file.path
            # 删除附件
            attachment.delete()
            # 检查文件夹是否为空，如果为空则删除文件夹
            folder_path = os.path.dirname(attachment_file_path)
            if not os.listdir(folder_path):  # 如果文件夹为空
                os.rmdir(folder_path)
            return redirect('literature:literature_detail', pk=literature.pk)
            
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            attachment = form.save(commit=False)
            attachment.literature = literature
            attachment.save()
            return redirect('literature:literature_detail', pk=literature.pk)
    else:
        form = AttachmentForm()
    return render(request, 'literature/literature_detail.html', {'literature': literature, 'attachments': attachments, 'form': form})

def upload_attachment(request, pk):
    literature = get_object_or_404(Literature, pk=pk)
    if request.method == "POST":
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            attachment = form.save(commit=False)
            attachment.literature = literature
            attachment.save()
            return redirect('literature_detail', pk=literature.pk)
    else:
        form = AttachmentForm()
    return render(request, 'literature/upload_attachment.html', {'form': form, 'literature': literature})

@receiver(post_delete, sender=Attachment)
def delete_attachment_file(sender, instance, **kwargs):
    # 删除文件系统中的附件文件
    instance.file.delete(save=False)

def import_literature_from_csv(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            if 'Title' in row and row['Title']:
                title = row['Title']
                doi = row.get('DOI', '')  # 注意此处使用 'doi'
                
                # 检查是否存在项目信息，如果存在则关联到文献上
                project_name = row.get('project', '')  # 假设项目信息在CSV中的字段名为 'project'
                if project_name:
                    project, _ = Project.objects.get_or_create(name=project_name)

                # 检查数据库中是否已存在相同的 DOI
                if Literature.objects.filter(doi=doi).exists():
                    print(f"Skipping row with existing DOI: {doi}")
                    continue
                
                # 创建新的 Literature 实例并保存
                literature = Literature(
                    title=title,
                    journal_abbr=row.get('journal_abbr', ''),
                    publication_year=row.get('publication_year', ''),
                    doi=doi
                )
                              
                literature.save()
                literature.projects.set([project])
            else:
                print("Skipping row with empty title:", row)


def literature_import(request):
    if request.method == 'POST' and request.FILES['csv_file']:
        csv_file = request.FILES['csv_file']
        fs = FileSystemStorage()
        filename = fs.save(csv_file.name, csv_file)
        file_path = os.path.join(fs.location, filename)
        import_literature_from_csv(file_path)
        fs.delete(filename)  # 删除临时文件
        return redirect('literature:literature_list')
    return render(request, 'literature/literature_import.html')

literature/templates/literature/index.html
{% extends 'base_generic.html' %}

{% block title %}Index Page{% endblock %}


{% block content %}
<div class="container pt-5 pb-4" data-aos="fade-up">

	<div class="card-deck card-pricing text-center">
		<div class="card border-0 shadow-sm">
			<div class="card-header bg-indigo border-0 pt-4 pb-4 text-white">
				<h2 class="my-0 font-weight-normal mb-3">Personal</h2>
				<h4 class="card-title pricing-card-title">$11 <small class="text-white">/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>10 users included</li>
					<li>2 GB of storage</li>
					<li>Email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-indigo btn-round">Start Free</button>
			</div>
		</div>
		<div class="card border-0 shadow-sm">
			<div class="card-header bg-info border-0 pt-4 pb-4">
				<h2 class="my-0 font-weight-normal mb-3">Premium</h2>
				<h4 class="card-title pricing-card-title">$15 <small>/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>20 users included</li>
					<li>10 GB of storage</li>
					<li>Priority email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-info btn-round"><i class="fab fa-telegram mr-2"></i> Start Free</button>
			</div>
		</div>
		<div class="card border-0 shadow-sm">
			<div class="card-header border-0 pt-4 pb-4 bg-indigo text-white">
				<h2 class="my-0 font-weight-normal mb-3">Enterprise</h2>
				<h4 class="card-title pricing-card-title">$29 <small class="textwhite">/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>30 users included</li>
					<li>15 GB of storage</li>
					<li>Phone and email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-indigo btn-round">Contact us</button>
			</div>
		</div>
	</div>
</div>

<div class="container pt-5 pb-4" data-aos="fade-up">

	<div class="card-deck card-pricing text-center">
		<div class="card border-0 shadow-sm">
			<div class="card-header bg-indigo border-0 pt-4 pb-4 text-white">
				<h2 class="my-0 font-weight-normal mb-3">Personal</h2>
				<h4 class="card-title pricing-card-title">$11 <small class="text-white">/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>10 users included</li>
					<li>2 GB of storage</li>
					<li>Email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-indigo btn-round">Start Free</button>
			</div>
		</div>
		<div class="card border-0 shadow-sm">
			<div class="card-header bg-info border-0 pt-4 pb-4">
				<h2 class="my-0 font-weight-normal mb-3">Premium</h2>
				<h4 class="card-title pricing-card-title">$15 <small>/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>20 users included</li>
					<li>10 GB of storage</li>
					<li>Priority email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-info btn-round"><i class="fab fa-telegram mr-2"></i> Start Free</button>
			</div>
		</div>
		<div class="card border-0 shadow-sm">
			<div class="card-header border-0 pt-4 pb-4 bg-indigo text-white">
				<h2 class="my-0 font-weight-normal mb-3">Enterprise</h2>
				<h4 class="card-title pricing-card-title">$29 <small class="textwhite">/ mo</small></h4>
			</div>
			<div class="card-body">
				<ul class="list-unstyled mt-3 mb-4">
					<li>30 users included</li>
					<li>15 GB of storage</li>
					<li>Phone and email support</li>
					<li>Help center access</li>
				</ul>
				<button type="button" class="btn btn-indigo btn-round">Contact us</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}

literature/templates/literature/literature_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Delete</title>
</head>
<body>
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete "{{ literature.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
    <a href="{% url 'literature:literature_detail' pk=literature.pk %}">Cancel</a>
</body>
</html>

literature/templates/literature/literature_detail.html
{% extends 'base_generic.html' %}

{% load custom_filters %}

{% block content %}
<div class="page">
<div class="layout-fluid">
    <div class="page-wrapper">
        <div class="page-header d-print-none">
            <div class="container-xl">
                <div class="row g-2 align-items-center">
                    <div class="col">
                        <h2 class="page-title">
                            Literature Detail
                        </h2>
                    </div>
                </div>
                <div class="row g-2 align-items-center">
                    <div class="row row-cards">
                        <div class="col-lg-8">
                            <div class="card">
                                <div class="table-responsive">
                                    <div class="card-header">
                                        <h3 class="card-title">{{ literature.title }}</h3>
                                    </div>
                                    <div class="card-body">
                                        <div class="datagrid">
                                            <div class="datagrid-item">
                                                <div class="datagrid-title">Journal</div>
                                                <div class="datagrid-content">{{ literature.journal_abbr }}</div>
                                            </div>
                                            <div class="datagrid-item">
                                                <div class="datagrid-title">Publication Year</div>
                                                <div class="datagrid-content">{{ literature.publication_year }}</div>
                                            </div>
                                            <div class="datagrid-item">
                                                <div class="datagrid-title">DOI</div>
                                                <div class="datagrid-content">{{ literature.doi }}</div>
                                            </div>
                                            <div class="datagrid-item">
                                                {% if literature.projects.all %}
                                                <div class="datagrid-title">Projects</div>
                                                {% for project in literature.projects.all %}
                                                <div class="datagrid-content">{{ project.name }}</div>
                                                <!-- Add any other project-related fields here -->
                                                {% endfor %}
                                                {% else %}
                                                <div class="datagrid-content">No projects associated with this
                                                    literature.</div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Attachments</h3>
                                </div>
                                <div class="list-group list-group-flush list-group-hoverable">
                                    {% for attachment in attachments %}
                                    <div class="list-group-item">
                                      <div class="row align-items-center">
                                        <div class="col-auto">{{ forloop.counter }}</span></div>
                                        <div class="col text-truncate">
                                          <a href="{{ attachment.file.url }}"" class="text-reset d-block">{{ attachment.file.name|basename}}</a>
                                          <div class="d-block text-muted text-truncate mt-n1">{{ attachment.uploaded_at }}</div>
                                          <div class="d-block text-muted text-truncate mt-n1">{{ attachment.description }}</div>
                                        </div>
                                        <div class="col-auto">
                                            <div class="text-body-secondary">
                                                <form method="post"
                                                    action="{% url 'literature:literature_detail' pk=literature.pk %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="delete_attachment"
                                                        value="{{ attachment.id }}">
                                                    <button class="btn btn-outline-danger btn-sm"
                                                        type="submit">Delete</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <div class="card-body">
                                    <form class="dropzone" method="post" enctype="multipart/form-data"
                                        action="{% url 'literature:literature_detail' pk=literature.pk %}">
                                        {% csrf_token %}
                                        <div class="fallback">
                                            {{ form.as_p }}
                                            <button type="submit">Upload</button>
                                    </form>
                                </div>
                                <div class="card-body">
                                    <div class="row g-2 align-items-center">
                                        <div class="col-6 col-sm-4 col-md-2 col-xl py-3">
                                            <a href="#" class="btn btn-outline-primary w-100">
                                              Noting Now!
                                            </a>
                                        </div>
                                        <div class="col-6 col-sm-4 col-md-2 col-xl py-3">
                                            <a href="{% url 'literature:literature_update' pk=literature.pk %}" class="btn btn-outline-warning w-100">
                                              Edit
                                            </a>
                                        </div>
                                        <div class="col-6 col-sm-4 col-md-2 col-xl py-3">
                                            <a href="{% url 'literature:literature_delete' literature.pk %}" class="btn btn-outline-danger w-100">
                                              Delete
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'literature:literature_list' %}">Back to Literature List</a>
</div>
</div>
</div>

</div>

{% endblock %}

literature/templates/literature/literature_import.html
{% extends 'base_generic.html' %}

{% block title %}Index Page{% endblock %}


{% block content %}
<div class="page">
    <div class="page-wrapper">
        <!-- Page header -->
        <div class="page-header d-print-none">
            <div class="container-xl">
                <div class="row g-2 align-items-center">
                    <div class="col">
                        <h2 class="page-title">
                            {% if form.instance.pk %}Edit Current{% else %}Add New{% endif %} Literature
                        </h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="page-body">
            <div class="container-xl">
                <div class="row row-cards">
                    <div class="col-md-12">
                      <div class="card">
                        <div class="card-body">
                          <form method="post" enctype="multipart/form-data"
                                action="{% url 'literature:literature_import' %}">
                                {% csrf_token %}
                                <label for="csv_file">Upload CSV file:</label>
                                <input type="file" id="csv_file" name="csv_file">
                                <button type="submit">Import</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>


<a href="{% url 'literature:literature_list' %}">Back to list</a>

{% endblock %}




    

literature/templates/literature/literature_list.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="layout-fluid">
<div class="page-wrapper">
    <!-- Page header -->
    <div class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col">
                    <h2 class="page-title">
                        All Literatures
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <!-- Page body -->
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-cards">
                <div class="col-12">
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-vcenter card-table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Journal Abbreviation</th>
                                        <th scope="col">Attachment</th>
                                        <th scope="col">DOI</th>
                                        <th scope="col">Projects</th>
                                        <th class="w-1"></th>
                                    </tr>
                                </thead>
                                <tbody id="literature-table-body">
                                    {% for literature in literatures %}
                                    <tr id="literature-row-{{ literature.pk }}">
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td><a href="{% url 'literature:literature_detail' literature.pk %}">{{ literature.title }}</a></td>
                                        <td>{{ literature.journal_abbr }}</td>
                                        <td>{% if literature.has_attachments %}Yes{% else %}No{% endif %}</td>
                                        <td>{{ literature.doi }}</td>
                                        <td>{% for project in literature.projects.all %}
                                            {{ project.name }}
                                            {% endfor %}
                                        </td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                                    onclick="window.location='{% url 'literature:literature_update' literature.pk %}'">
                                                    <span data-feather="edit"></span>
                                                    Edit
                                                </button>
                                                <button type="button" class="btn btn-sm btn-outline-secondary"
                                                    onclick="confirmDelete({{ literature.pk }})">
                                                    <span data-feather="trash-2"></span>
                                                    Delete
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script>
    function confirmDelete(pk) {
        if (confirm("确定要删除这条记录吗？")) {
            const csrfToken = '{{ csrf_token }}';
            fetch(`{% url 'literature:literature_delete' pk=0 %}`.replace('0', pk), {
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': csrfToken,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ pk: pk })
            })
            .then(response => {
                if (response.ok) {
                    document.getElementById(`literature-row-${pk}`).remove();
                } else {
                    alert('Failed to delete the record.');
                }
            })
            .catch(error => console.error('Error:', error));
        }
    }
</script>

{% endblock %}

literature/templates/literature/upload_attachment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Attachment</title>
</head>
<body>
    <h1>Upload Attachment</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>